// LimeChat is copyrighted free software by Satoshi Nakagawa <psychs AT limechat DOT net>.
// You can redistribute it and/or modify it under the terms of the GPL version 2 (see the file GPL.txt).

#define ADMIN		@"ADMIN"
#define AWAY		@"AWAY"
#define ERROR		@"ERROR"
#define INVITE		@"INVITE"
#define INFO		@"INFO"
#define ISON		@"ISON"
#define JOIN		@"JOIN"
#define KICK		@"KICK"
#define KILL		@"KILL"
#define LINKS		@"LINKS"
#define LIST		@"LIST"
#define LUSERS		@"LUSERS"
#define MODE		@"MODE"
#define MOTD		@"MOTD"
#define NAMES		@"NAMES"
#define NICK		@"NICK"
#define NOTICE		@"NOTICE"
#define OPER		@"OPER"
#define PART		@"PART"
#define PASS		@"PASS"
#define PING		@"PING"
#define PONG		@"PONG"
#define PRIVMSG		@"PRIVMSG"
#define QUIT		@"QUIT"
#define STATS		@"STATS"
#define TOPIC		@"TOPIC"
#define TRACE		@"TRACE"
#define USER		@"USER"
#define VERSION		@"VERSION"
#define WHO			@"WHO"
#define WHOIS		@"WHOIS"
#define WHOWAS		@"WHOWAS"
#define CAP			@"CAP"
#define AUTHENTICATE	@"AUTHENTICATE"

#define ACTION		@"ACTION"
#define DCC			@"DCC"
#define SEND		@"SEND"

#define CLIENTINFO	@"CLIENTINFO"
#define CTCP		@"CTCP"
#define CTCPREPLY	@"CTCPREPLY"
#define TIME		@"TIME"
#define USERINFO	@"USERINFO"

#define OMSG		@"OMSG"
#define ONOTICE		@"ONOTICE"

#define BAN			@"BAN"
#define CLEAR		@"CLEAR"
#define CLOSE		@"CLOSE"
#define CYCLE		@"CYCLE"
#define DEHALFOP	@"DEHALFOP"
#define DEOP		@"DEOP"
#define DEVOICE		@"DEVOICE"
#define HALFOP		@"HALFOP"
#define HOP			@"HOP"
#define IGNORE		@"IGNORE"
#define J			@"J"
#define LEAVE		@"LEAVE"
#define M			@"M"
#define ME			@"ME"
#define MSG			@"MSG"
#define OP			@"OP"
#define RAW			@"RAW"
#define REJOIN		@"REJOIN"
#define QUERY		@"QUERY"
#define QUOTE		@"QUOTE"
#define T			@"T"
#define TIMER		@"TIMER"
#define VOICE		@"VOICE"
#define UNBAN		@"UNBAN"
#define UNIGNORE	@"UNIGNORE"
#define UMODE		@"UMODE"
#define WEIGHTS		@"WEIGHTS"
	
#define IRC_PENALTY_NORMAL	2
#define IRC_BODY_LEN		500
#define IRC_ADDRESS_LEN		50
