// Created by Satoshi Nakagawa.
// You can redistribute it and/or modify it under the Ruby's license or the GPL2.

#define PRIVMSG		@"PRIVMSG"
#define NOTICE		@"NOTICE"
#define JOIN		@"JOIN"
#define PART		@"PART"
#define KICK		@"KICK"
#define QUIT		@"QUIT"
#define KILL		@"KILL"
#define NICK		@"NICK"
#define MODE		@"MODE"
#define TOPIC		@"TOPIC"
#define INVITE		@"INVITE"
#define ERROR		@"ERROR"
#define PING		@"PING"
#define PONG		@"PONG"
#define NAMES		@"NAMES"
#define WHO			@"WHO"
#define USER		@"USER"
#define PASS		@"PASS"
#define LIST		@"LIST"
#define WHOIS		@"WHOIS"
#define WHOWAS		@"WHOWAS"
#define ISON		@"ISON"

#define ACTION		@"ACTION"
#define VERSION		@"VERSION"
#define QUERY		@"QUERY"
#define ME			@"ME"
#define MSG			@"MSG"
#define CTCP		@"CTCP"
#define QUOTE		@"QUOTE"
#define RAW			@"RAW"
#define M			@"M"
#define J			@"J"
#define T			@"T"
#define LEAVE		@"LEAVE"
#define REJOIN		@"REJOIN"
#define HOP			@"HOP"
#define CYCLE		@"CYCLE"

#define IRC_PENALTY_NORMAL	2
